### ISSUE TITLE
Centrer les menus

### ISSUE THREAD

**Issue by c-fabre** [open-src-soc/open-src-soc.github.io#1]
La bare des menus en haut est justfiée à gauche. Ces rencontres étant apolitiques, il conviendrait que ces menus occupent toute la largeur laissée libre sur la page.

**Comment by damiencourousse** [comment]
Le site s'appuie sur pure CSS.
À ma connaissance, le système de menus ne permet pas de centrer le contenu, sans modification du contenu CSS.  https://purecss.io/menus
